server:
  port: 8080 #실행할 포트로 설정
spring:
  config:
    import: optional:file:backend/user-service/.env[.properties]
  application:
    name: user-service #현재 서비스 이름으로 변경
  datasource:
    #로컬에서 사용할 db로 설정, account 부분을 서비스 이름으로 변경
    url: jdbc:mysql://localhost:3306/petsi_user?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ssafy
  flyway:
    enabled: false #dev에서는 편안한 옵션 선택
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create #dev에서는 편안한 옵션 선택
      format_sql: true
##swagger : account 부분 서비스로 변경
#springdoc:
#  swagger-ui:
#    path: /api/v1/user/swagger-ui.html

#로그 관련
logging:
  level:
    org.hibernate: DEBUG
    org.springframework: DEBUG
fin:
  api-url: "https://finopenapi.ssafy.io/ssafy/api/v1/member/"
  api_key: ${FIN_API_KEY}
keycloak:
  realm: petsi
  auth-server-url: http://localhost:8082
  resource: user-service
  credentials:
    secret: ${USER_KEYCLOAK_SECRET}
  ssl-required: external