server:
  port: 9005 #실행할 포트로 설정
spring:
  config:
    import: optional:file:.env
  application:
    name: expense-service #현재 서비스 이름으로 변경
  datasource:
    #로컬에서 사용할 db로 설정, account 부분을 서비스 이름으로 변경
    url: jdbc:mysql://localhost:3306/petsi_expense?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    enabled: false #dev에서는 편안한 옵션 선택
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none #dev에서는 편안한 옵션 선택
      format_sql: true

#swagger : account 부분 서비스로 변경
springdoc:
  swagger-ui:
    path: /api/v1/expense/swagger-ui.html

#로그 관련
logging:
  level:
    org.hibernate: DEBUG
    org.springframework: DEBUG

cloud:
  aws:
    s3:
      bucket: petsi-images-bucket
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}