server:
  port: 80

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://petsi/user-service:9001
          predicates:
            - Path=/user/**
        - id: pet-service
          uri: http://petsi/pet-service:9002
          predicates:
            - Path=/pet/**
        - id: account-service
          uri: http://petsi/account-service:9003
          predicates:
            - Path=/account/**
        - id: picture-service
          uri: http://petsi/picture-service:9004
          predicates:
            - Path=/account/**
        - id: expense-service
          uri: http://petsi/expense-service:9005
          predicates:
            - Path=/account/**
        - id: schedule-service
          uri: http://petsi/schedule-service:9006
          predicates:
            - Path=/account/**
        - id: notification-service
          uri: http://petsi/notification-service:9007
          predicates:
            - Path=/account/**
        - id: frontend-s3
          uri: https://petsi-frontend-bucket.s3.amazonaws.com
          predicates:
            - Path=/**