server:
  port: 80
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

spring:
  application:
    name: gateway-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s
        pool:
          type: elastic
          max-idle-time: 15s
          max-life-time: 60s
      routes:
        - id: user-service
          uri: http://j11a403.p.ssafy.io:9001
          predicates:
            - Path=/user/**
        - id: pet-service
          uri: http://j11a403.p.ssafy.io:9002
          predicates:
            - Path=/pet/**
        - id: account-service
          uri: http://j11a403.p.ssafy.io:9003
          predicates:
            - Path=/account/**
        - id: picture-service
          uri: http://j11a403.p.ssafy.io:9004
          predicates:
            - Path=/picture/**
        - id: expense-service
          uri: http://j11a403.p.ssafy.io:9005
          predicates:
            - Path=/expense/**
        - id: schedule-service
          uri: http://j11a403.p.ssafy.io:9006
          predicates:
            - Path=/schedule/**
        - id: notification-service
          uri: http://j11a403.p.ssafy.io:9007
          predicates:
            - Path=/notification/**
        - id: frontend-s3
          uri: http://petsi-frontend-bucket.s3-website.ap-northeast-2.amazonaws.com/
          predicates:
            - Path=/, /*, /assets/**, /fonts/**, /images/**, index.html, /*.css, /*.js, /*.ts, /*.tsx, /Symbol.ico
          filters:
            - RewritePath=/.*,/index.html