server:
  port: 80
  shutdown: graceful
  connection-timeout: 60s

spring:
  application:
    name: gateway-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      mvc:
        timeout:
          connect-timeout: 30000ms
          response-timeout: 120000ms
        routes:
          - id: user-service
            uri: http://petsi/user-service:9001
            predicates:
              - Path=/api/v1/user/**
          - id: pet-service
            uri: http://petsi/pet-service:9002
            predicates:
              - Path=/api/v1/pet/**
          - id: account-service
            uri: http://petsi/account-service:9003
            predicates:
              - Path=/api/v1/account/**
          - id: picture-service
            uri: http://petsi/picture-service:9004
            predicates:
              - Path=/api/v1/picture/**
          - id: expense-service
            uri: http://petsi/expense-service:9005
            predicates:
              - Path=/api/v1/expense/**
          - id: schedule-service
            uri: http://petsi/schedule-service:9006
            predicates:
              - Path=/api/v1/schedule/**
          - id: notification-service
            uri: http://petsi/notification-service:9007
            predicates:
              - Path=/api/v1/notification/**
          - id: frontend-s3
            uri: http://petsi-frontend-bucket.s3-website.ap-northeast-2.amazonaws.com/
            predicates:
              - Path=/index.html, /static/**, /*.js, /*.css, /*.png, /*.jpg, /*.gif

security:
  basic:
    enabled: false

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
