server:
  port: 9002 #실행할 포트로 설정
spring:
  config:
    import: optional:file:.env
  application:
    name: pet-service #현재 서비스 이름으로 변경
  datasource:
    #로컬에서 사용할 db로 설정, account 부분을 서비스 이름으로 변경
    url: jdbc:mysql://localhost:3306/petsi_pet?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: petsi
    password: petsi0909!
  flyway:
    enabled: false #dev에서는 편안한 옵션 선택
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none #dev에서는 편안한 옵션 선택
      format_sql: true

#swagger : account 부분 서비스로 변경
springdoc:
  swagger-ui:
    path: /api/v1/pet/swagger-ui.html

#로그 관련
logging:
  level:
    org.hibernate: DEBUG
    org.springframework: DEBUG

cloud:
  aws:
    s3:
      bucket: petsi-images-bucket
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: 515355
      secretKey: 9j7yqLt4qpllFC/9NwZoiX+fEQOemVcHJu5dcE/1

# Eureka 서버 주소
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/